### ISSUE TITLE
[ SUGGESTION ] Buttons

### ISSUE THREAD

**Issue by MEZBATHEKING** [chethanyadav456/Giveaway#2]
Replace reaction type of Giveaways into buttons? Like tap a button for join giveaways!

**Comment by chethanyadav456** [comment]
> Replace reaction type of Giveaways into buttons? Like tap a button for join giveaways!

Yes sure I can but I am really busy with my studies when I get time in weekends I will try to do that.

If anyone can contribute to this project would be good.
